version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: quiz-app-postgres-dev
    restart: always
    environment:
      POSTGRES_USER: qa-user
      POSTGRES_PASSWORD: qa-password
      POSTGRES_DB: qa-db
    ports:
      - "5432:5432"
    networks:
      - quiz-app-network
    volumes:
      - quiz-app-postgres:/var/lib/postgresql/data

  prometheus:
    container_name: quiz-app-prometheus-dev
    image: prom/prometheus:v2.44.0
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    volumes:
      - ./prometheus/:/etc/prometheus/
    networks:
      - quiz-app-network

  grafana:
    image: grafana/grafana:9.5.2
    user: "$UID:$GID"
    container_name: quiz-app-grafana-dev
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
    networks:
      - quiz-app-network

volumes:
  quiz-app-postgres:

networks:
  quiz-app-network:
    driver: bridge