spring:
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  datasource:
    username: qa-user
    password: qa-password
    url: jdbc:postgresql://localhost:5432/qa-db-prod

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

quiz:
  files-folder: prod/
  profiling: false
  monitoring: false

vaadin:
  productionMode: true

logging:
  level:
    org.rsinitsyn.quiz: INFO