spring:
#  devtools:
#    livereload:
#      enabled: true
#      port: 35730
#    restart:
#      poll-interval: 2s
#      quiet-period: 1s
#      enabled: true

  # DB properties
  datasource:
    url: jdbc:h2:file:./db/quiz-db-dev;AUTO_SERVER=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      # TODO none
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

quiz:
  files-folder: dev/
  profiling: false

logging:
  level:
    org.rsinitsyn.quiz: DEBUG