spring:
  application:
    name: quiz-app
  devtools:
    livereload:
      enabled: false
      port: 35730
    restart:
      poll-interval: 2s
      quiet-period: 1s
      enabled: false

  # DB properties
  datasource:
    username: qa-user
    password: qa-password
    url: jdbc:postgresql://localhost:5432/qa-db

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # TODO none
      ddl-auto: validate
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy # underscore
    show-sql: true
    open-in-view: false

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    contexts: ${spring.profiles.active}

quiz:
  openai:
    enabled: false
    apiKey: TODO_MOVE_TO_ENV_VARIABLES
    model: gpt-3.5-turbo
    url: https://api.openai.com/v1/chat/completions
  files-folder: dev/
  profiling: false
  monitoring: false
  job:
    cleanupCleverestGames: false
    uCarNumberGeneratorJob: false

management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [ 'health', 'info', 'metrics', 'prometheus' ]

logging:
  level:
    org.rsinitsyn.quiz: TRACE