spring:
  datasource:
    url: jdbc:h2:file:./db/quiz-db-dev;AUTO_SERVER=TRUE
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: false

quiz:
  audio-folder: dev/
  profiling: false