spring:
  application:
    name: quiz-app
    devtools:
      livereload:
        enabled: true
        port: 35730
      restart:
        poll-interval: 2s
        quiet-period: 1s
        enabled: true

  # DB properties
  datasource:
    url: jdbc:h2:file:./db/quiz-db-dev;AUTO_SERVER=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      # TODO none
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: ${quiz.profiling}
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

quiz:
  openai:
    enabled: false
    apiKey: TODO_MOVE_TO_ENV_VARIABLES
    model: gpt-3.5-turbo
    url: https://api.openai.com/v1/chat/completions
  files-folder: dev/
  profiling: false
  monitoring: false
  job:
    cleanupCleverestGames: true
    uCarNumberGeneratorJob: false

management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: [ 'health', 'info', 'metrics', 'prometheus' ]

logging:
  #  pattern:
  #    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    org.rsinitsyn.quiz: DEBUG