scrape_configs:
  - job_name: 'quiz-app-scrape'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      # When Prometheus is running in Docker, use host.docker.internal as the target
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'quiz-app'